# Filename: production.gcp.yml
plugin: google.cloud.gcp_compute
projects:
  - niveus-infra-ai-tools
auth_kind: application
regions:
  - asia-south1
filters:
  # Only discover running instances
  - status = RUNNING

# Dynamically create groups based on GCP labels
# e.g., A VM with the label "role: zookeeper" will be added to the 'zookeeper_servers' group.
groups:
  zookeeper_servers: "labels.role == 'zookeeper'"
  kafka_servers: "labels.role == 'kafka-broker'"
  kafka_client: "labels.role == 'kafka-client'"

# Dynamically create Ansible variables from instance metadata and labels
compose:
  # Set the connection host to the instance's internal IP address
  ansible_host: networkInterfaces[0].networkIP

  # Create Ansible host variables directly from GCP labels on each VM.
  # Note: Values from labels are always strings.
  zookeeper_myid: labels.zookeeper_myid
  kafka_broker_id: labels.kafka_broker_id