# Clustering Configuration
rabbitmq_cluster_name: "mahesha"
rabbitmq_cluster_enabled: true
rabbitmq_cluster_discovery_backend: "rabbit_peer_discovery_classic_config"
rabbitmq_cluster_nodes: >-
  {{ groups['rabbitmq']
     | map('extract', hostvars, ['name'])
     | map('regex_replace', '^(.*)$', 'rabbit@\\1')
     | difference(['rabbit@' + hostvars[inventory_hostname].name])
     | list }}
# rabbitmq_primary: "{{ [groups['rabbitmq'][0]] }}"
# rabbitmq_secondary: "{{ groups['rabbitmq'][1:] }}"

# Security Configuration
rabbitmq_allow_guest_loopback: false

# SSL/TLS Configuration
rabbitmq_enable_tls: false
rabbitmq_ssl_port: 5671
rabbitmq_ssl_verify: "verify_peer"
rabbitmq_ssl_fail_if_no_peer_cert: true
rabbitmq_management_ssl_port: 15671

# SSL Certificate Paths (when TLS is enabled)
rabbitmq_ssl_cacert_file: "/etc/rabbitmq/ssl/ca_certificate.pem"
rabbitmq_ssl_cert_file: "/etc/rabbitmq/ssl/server_certificate.pem"
rabbitmq_ssl_key_file: "/etc/rabbitmq/ssl/server_key.pem"

# Logging Configuration
rabbitmq_log_console: false
rabbitmq_log_level: "info"
rabbitmq_log_file: "/var/log/rabbitmq/rabbit.log"

# Performance Configuration
rabbitmq_memory_high_watermark: "0.6"
rabbitmq_disk_free_limit: "1.0"
rabbitmq_channel_max: 2047
rabbitmq_connection_max: 65535
rabbitmq_heartbeat: 60

# High Availability (HA) Policy
# This policy ensures all queues are mirrored across 2 nodes.
rabbitmq_ha_policy_name: "ha-all"
rabbitmq_ha_policy_pattern: ".*" # Apply to all queues
rabbitmq_ha_policy_definition:
  ha-mode: "exactly"
  ha-params: 2
  ha-sync-mode: "automatic"

# Performance Tuning
# Set the maximum number of file descriptors for the RabbitMQ process.
# This is critical for handling a large number of concurrent connections.
rabbitmq_open_file_limit: 65536