---
# ============================================================================
# RabbitMQ Installation - Per-Host Confirmation Control
# ============================================================================

# OS and Version Compatibility Matrix (GCP-focused)
- name: Set compatible RabbitMQ versions based on OS and architecture
  set_fact:
    compatible_versions: >-
      {% if (ansible_distribution == 'Ubuntu' and ansible_distribution_release in ['focal', 'jammy', 'noble']) or
            (ansible_distribution == 'Debian' and ansible_distribution_release in ['bullseye', 'bookworm']) %}
        {% if ansible_architecture == 'x86_64' %}
          ['4.1.3', '4.1.2', '4.1.1', '4.1.0']
        {% elif ansible_architecture == 'aarch64' %}
          ['4.1.3', '4.1.2', '4.1.1', '4.1.0']
        {% else %}
          []
        {% endif %}
      {% elif ansible_distribution in ['RedHat', 'CentOS', 'Rocky', 'OracleLinux', 'AlmaLinux'] and ansible_distribution_major_version in ['8', '9'] %}
        {% if ansible_architecture == 'x86_64' %}
          ['4.1.3', '4.1.2', '4.1.1', '4.1.0']
        {% elif ansible_architecture == 'aarch64' %}
          ['4.1.3', '4.1.2', '4.1.1', '4.1.0']
        {% else %}
          []
        {% endif %}
      {% elif ansible_distribution == 'Fedora' and ansible_distribution_major_version | int >= 39 %}
        ['4.1.3', '4.1.2', '4.1.1', '4.1.0']
      {% else %}
        []
      {% endif %}

- name: Display detected system information
  debug:
    msg: |
      Detected System Information:
        - OS: {{ ansible_distribution }} {{ ansible_distribution_release | default(ansible_distribution_major_version) }}
        - Architecture: {{ ansible_architecture }}
        - Host: {{ inventory_hostname }}
  tags: ['rabbitmq', 'info']

- name: Verify user-specified RabbitMQ version is compatible
  fail:
    msg: |
      ❌ INCOMPATIBLE RABBITMQ VERSION ❌
      Requested Version: {{ rabbitmq_version }}
      Host: {{ inventory_hostname }}
      Compatible versions: {{ compatible_versions | join(', ') }}
  when: rabbitmq_version not in compatible_versions
  tags: ['rabbitmq', 'validation']

# Set final installation facts
- name: Finalize RabbitMQ installation facts
  set_fact:
    selected_version: "{{ rabbitmq_version }}"
    package_manager: "{{ 'apt' if ansible_distribution in ['Ubuntu', 'Debian'] else 'yum' }}"
  when: host_upgrade_confirmed | default(true)
  tags: ['rabbitmq', 'facts']

- name: Display installation plan
  debug:
    msg: |
      🚀 RabbitMQ Installation Plan for {{ inventory_hostname }}:
        - Target Version: {{ selected_version }}
        - Package Manager: {{ package_manager }}
        - Status: {{ 'PROCEEDING' if host_upgrade_confirmed | default(false) else 'SKIPPED' }}
  when: host_upgrade_confirmed | default(true)
  tags: ['rabbitmq', 'info']

# Include platform-specific installation tasks (only if confirmed)
- name: Include platform-specific installation tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "unsupported_os.yml"
  when: host_upgrade_confirmed | default(true)
  tags: ['rabbitmq', 'install']

# Final status for processed hosts
- name: Display installation completion status
  debug:
    msg: |
      ✅ RabbitMQ {{ selected_version }} Installation Complete on {{ inventory_hostname }}!
      
      🌐 Access Information:
        - AMQP Port: {{ rabbitmq_tcp_port | default('5672') }}
        - Management UI: http://{{ ansible_default_ipv4.address }}:{{ rabbitmq_management_port | default('15672') }}
        - Admin User: {{ rabbitmq_admin_user }}
  when: host_upgrade_confirmed | default(true)
  tags: ['rabbitmq', 'summary']