---
- name: Phase 1 - Install and Configure RabbitMQ on all nodes
  hosts: rabbitmq
  become: true
  roles:
    - role: rabbitmq
  tags:
  - install

- name: Phase 2 - Build, Harden, and Verify the Cluster
  hosts: rabbitmq
  become: true
  serial: 1 # This is a critical safety measure
  roles:
    - role: rabbitmq_cluster
  tags:
    - cluster 