---
- name: Phase 1 - Install and Configure RabbitMQ on all nodes
  hosts: rabbitmq_cluster
  become: true
  roles:
    - role: rabbitmq

- name: Phase 2 - Build, Harden, and Verify the Cluster
  hosts: rabbitmq_cluster
  become: true
  serial: 1 # This is a critical safety measure
  roles:
    - role: rabbitmq_cluster