---
- name: Uninstall RabbitMQ from target nodes
  hosts: rabbitmq
  become: true
  tasks:
    - name: Stop RabbitMQ service
      systemd:
        name: rabbitmq-server
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Remove RabbitMQ package (Debian/Ubuntu)
      apt:
        name: rabbitmq-server
        state: absent
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove Erlang packages (Debian/Ubuntu)
      apt:
        name: erlang*
        state: absent
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove RabbitMQ and Erlang packages (RHEL/CentOS)
      yum:
        name:
          - rabbitmq-server
          - erlang
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove RabbitMQ config and data directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rabbitmq
        - /var/lib/rabbitmq
      loop_control:
        loop_var: dir_to_remove