---
- name: Uninstall RabbitMQ and all related components
  hosts: rabbitmq
  connection: gcp_ssh
  become: true
  tasks:
    - name: Stop and disable RabbitMQ service
      systemd:
        name: rabbitmq-server
        state: stopped
        enabled: no
      ignore_errors: true

    # --- Debian/Ubuntu Uninstallation ---
    - name: Remove RabbitMQ and Erlang packages (Debian/Ubuntu)
      apt:
        name:
          - rabbitmq-server
          - erlang*
        state: absent
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove RabbitMQ repository file (Debian/Ubuntu)
      file:
        path: /etc/apt/sources.list.d/rabbitmq.list
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove RabbitMQ GPG signing key (Debian/Ubuntu)
      file:
        path: /usr/share/keyrings/com.rabbitmq.team.gpg
        state: absent
      when: ansible_os_family == "Debian"

    - name: Run apt-get update after removal (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    # --- RHEL/CentOS Uninstallation ---
    - name: Remove RabbitMQ and Erlang packages (RHEL/CentOS)
      yum:
        name:
          - rabbitmq-server
          - erlang
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove RabbitMQ repository files (RHEL/CentOS)
      file:
        path: "{{ repo_file }}"
        state: absent
      loop:
        - /etc/yum.repos.d/modern-erlang.repo
        - /etc/yum.repos.d/modern-erlang-noarch.repo
        - /etc/yum.repos.d/rabbitmq-el8.repo
        - /etc/yum.repos.d/rabbitmq-el8-noarch.repo
        - /etc/yum.repos.d/rabbitmq-el9.repo
        - /etc/yum.repos.d/rabbitmq-el9-noarch.repo
      loop_control:
        loop_var: repo_file
      when: ansible_os_family == "RedHat"

    # --- Common Cleanup ---
    - name: Remove RabbitMQ config and data directories
      file:
        path: "{{ dir_to_remove }}"
        state: absent
      loop:
        - /etc/rabbitmq
        - /var/lib/rabbitmq
      loop_control:
        loop_var: dir_to_remove